FROM ubuntu:focal

LABEL maintainer="Andrei.Shvarts@glasgow.ac.uk"

# general environment for docker
ENV DEBIAN_FRONTEND=noninteractive \
    SPACK_ROOT=/usr/local \
    FORCE_UNSAFE_CONFIGURE=1

# timezone env with default
ENV TZ Europe/London

# Config apt-get
RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99local

ENV DEBIAN_FRONTEND=noninteractive

# Install packages
RUN apt-get update && \
apt-get install -y \
vim \
file \
zlib1g-dev \
openssh-server \
wget \
valgrind \
curl \
git \
g++ \
gfortran \
gdb \
m4 \
automake \
build-essential \
libtool \
libblas-dev \
liblapack-dev \
libpython3.8-dev \
libsigsegv2 \
libjpeg-dev \
graphviz \
doxygen \
cmake \
pkg-config \
gnuplot \
ca-certificates \
python \
python-dev \
python3-distutils \
libx11-dev \
xauth \
xterm \
unzip \
mesa-common-dev \
libglu1-mesa-dev \
libxmu-dev \
libxi-dev \
libssl-dev \
gawk \
libopenmpi-dev \
&& rm -rf /var/lib/apt/lists/*

ENV INSTALL_DIR=/container

ENV TARGET=x86_64

# SSH .ssh dir
RUN mkdir root/.ssh

# Allow to trace child procsses needed for debuging
RUN sed  -i 's/kernel.yama.ptrace_scope = 1/kernel.yama.ptrace_scope = 0/' /etc/sysctl.d/10-ptrace.conf

# Create the PrivSep empty dir if necessary
RUN if [ ! -d /var/run/sshd ]; then \
   mkdir /var/run/sshd; \
   chmod 0755 /var/run/sshd; \
   fi

EXPOSE 22

RUN apt-get update && \
  apt-get install -y \
  python3-pip \
  libgl1-mesa-glx \
  libglu1-mesa \
  xvfb \
  build-essential \
  python3-dev \
  npm \
  nodejs \
  libnode64 \
  && apt-get clean && rm -rf /var/lib/apt/lists/*  

RUN ln -s `which pip3.8` /usr/bin/pip3.8

RUN pip3 -q install pip --upgrade && \
  pip3 install notebook 

RUN pip3 install \
  pandas \
  scipy \
  gmsh \
  jupytext \
  pyvista \
  pyvirtualdisplay \
  ipyvtklink \
  jupyter_contrib_nbextensions \
  itkwidgets \
  ipywidgets==7.7 \
  pythreejs \
  ipyvtk-simple \
  panel \
  jupyter-server \
  jupyter \
  'jupyterhub==3.1.1' \
  jupyterhub-firstuseauthenticator && \
  jupyter contrib nbextension install --sys-prefix && \
  jupyter nbextension install --py jupytext --sys-prefix && \
  jupyter nbextension enable --py jupytext && \
  jupyter nbextension install --py pythreejs --sys-prefix && \
  jupyter nbextension enable --py pythreejs && \
  npm install -g configurable-http-proxy

# allow jupyterlab for ipyvtk
ENV DISPLAY=:99.0
ENV PYVISTA_USE_IPYVTK=true
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/site-packages/gmsh-4.8.3-Linux64-sdk/lib
ENV JUPYTER_HOME_DIR=$INSTALL_DIR/jupyterhub

ADD jupyterhub $JUPYTER_HOME_DIR

WORKDIR $INSTALL_DIR

RUN useradd admin \
  -m -d $JUPYTER_HOME_DIR/admin \
  -k $JUPYTER_HOME_DIR/skel/ \
  -p paN8aiEIonqJE && \
  usermod -aG sudo admin

# Copy static styles for JupyterHub
RUN cp $JUPYTER_HOME_DIR/css/* /usr/local/share/jupyterhub/static/css

EXPOSE 8000
CMD ["/bin/bash", "-c", "jupyterhub -f ${JUPYTER_HOME_DIR}/jupyterhub_config.py"]
